# Generated by Django 5.0.4 on 2024-10-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.CreateModel(
            name='PickupStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(default=None, max_length=100)),
                ('town', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alisa.county')),
            ],
            options={
                'verbose_name': 'pickupstation',
                'verbose_name_plural': 'pickupstations',
                'ordering': ['station'],
            },
        ),
    ]
