# Generated by Django 5.0.4 on 2024-10-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alisa', '0002_county_product_brand_product_model_pickupstation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickupstation',
            options={'ordering': ['id'], 'verbose_name': 'pickupstation', 'verbose_name_plural': 'pickupstations'},
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(default=None, max_length=250)),
                ('station', models.CharField(default=None, max_length=250)),
                ('phone', models.CharField(default=None, max_length=13)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alisa.order')),
            ],
            options={
                'verbose_name': 'customer-address',
                'verbose_name_plural': 'customer-addresses',
                'ordering': ['order'],
            },
        ),
    ]
