# Generated by Django 5.0.4 on 2024-10-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alisa', '0006_foo_alter_category_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
    ]
